# Generated by Django 2.1.4 on 2019-01-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('tree_id', 'name'), 'verbose_name': 'Категория Сервис', 'verbose_name_plural': 'Категории Сервис'},
        ),
    ]
