# Generated by Django 2.1.4 on 2019-01-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20190128_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_Services',
        ),
    ]
