# Generated by Django 2.1.4 on 2019-01-28 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20190128_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_Services',
            new_name='CategoryService',
        ),
    ]
