# Generated by Django 2.1.4 on 2019-01-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20190128_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='model',
            field=models.CharField(blank=True, help_text='Модель товара', max_length=200),
        ),
        migrations.AddField(
            model_name='services',
            name='vendor',
            field=models.CharField(blank=True, help_text='Производитель', max_length=200),
        ),
    ]
