# Generated by Django 2.1.4 on 2019-01-27 12:52

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Category')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'ordering': ('tree_id', 'name'),
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название товара', max_length=400)),
                ('vendor_code', models.CharField(db_index=True, help_text='Артикул, парт номер', max_length=200)),
                ('vendor', models.CharField(blank=True, help_text='Производитель', max_length=200)),
                ('type_product', models.CharField(blank=True, help_text='Тип товара', max_length=200)),
                ('slug', models.SlugField(max_length=400)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('keywords', models.TextField(blank=True, help_text='Ключивые слова (тонер, материнская плата, пружина)')),
                ('description', models.TextField(blank=True, help_text='Описание товара')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена входящая', max_digits=10)),
                ('interest', models.DecimalField(blank=True, choices=[(Decimal('0.07'), '7%'), (Decimal('0.15'), '15%'), (Decimal('0.20'), '20%'), (Decimal('0.25'), '25%'), (Decimal('0.30'), '30%')], decimal_places=2, help_text='Процент, накрутка', max_digits=5, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Остатоки')),
                ('discount', models.DecimalField(decimal_places=2, blank=True, help_text='Процент, накрутка')),
                ('available', models.BooleanField(default=True, help_text='Доступен ли к заказу')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, help_text='дата обновления')),
                ('accessories', models.ManyToManyField(blank=True, related_name='_product_accessories_+', to='shop.Product')),
                ('category', models.ForeignKey(help_text='Каталог товара (расходные материалы, компьютеры и комплетующие и т д)', on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Список тегов, разделенных запятыми', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
                'verbose_name': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(blank=True, choices=[(Decimal('0.07'), '7%'), (Decimal('0.15'), '15%'), (Decimal('0.20'), '20%'), (Decimal('0.25'), '25%'), (Decimal('0.30'), '30%')], decimal_places=2, help_text='Процент скидка', max_digits=5, null=True)),
                ('available', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('stock_start', models.DateTimeField()),
                ('stock_end', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            options={
                'verbose_name_plural': 'Акции',
                'ordering': ('product',),
                'verbose_name': 'Акция',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=400)),
                ('vendor_code', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=400)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('accessories', models.ManyToManyField(blank=True, to='shop.Product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
                'ordering': ('name',),
                'verbose_name': 'Услуга',
            },
        ),
        migrations.AlterIndexTogether(
            name='services',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'slug')},
        ),
    ]
