# Generated by Django 2.1.4 on 2019-02-13 23:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='category/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('tree_id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название товара', max_length=400)),
                ('slug', models.SlugField(max_length=400)),
                ('vendor_code', models.CharField(db_index=True, help_text='Артикул, парт номер', max_length=200)),
                ('vendor', models.CharField(blank=True, help_text='Производитель', max_length=200)),
                ('format_fild', models.CharField(blank=True, choices=[('', ''), ('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('A8', 'A8'), ('A9', 'A9'), ('A10', 'A10')], help_text='A3,A4', max_length=50)),
                ('color_fild', models.CharField(blank=True, help_text='BW, Color', max_length=50)),
                ('specifications', models.TextField(blank=True, help_text='Характеристики товара')),
                ('type_product', models.CharField(blank=True, help_text='Тип товара', max_length=200)),
                ('keywords', models.TextField(blank=True, help_text='Ключивые слова')),
                ('description', models.TextField(blank=True, help_text='Описание товара')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена входящая', max_digits=10)),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Остатоки')),
                ('available', models.BooleanField(default=True, help_text='Доступен ли к заказу')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, help_text='дата обновления')),
                ('accessories', models.ManyToManyField(blank=True, related_name='_product_accessories_+', to='shop.Product')),
                ('category', models.ForeignKey(help_text='Каталог товара (расходные материалы, компьютеры и комплетующие и т д)', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.Category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(blank=True, choices=[(Decimal('0.07'), '7%'), (Decimal('0.15'), '15%'), (Decimal('0.20'), '20%'), (Decimal('0.25'), '25%'), (Decimal('0.30'), '30%')], decimal_places=2, help_text='Процент скидка', max_digits=5, null=True)),
                ('available', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('stock_start', models.DateTimeField()),
                ('stock_end', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ('product',),
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=400)),
                ('slug', models.SlugField(max_length=400)),
                ('vendor_code', models.CharField(blank=True, max_length=200)),
                ('vendor', models.CharField(blank=True, help_text='Производитель', max_length=200)),
                ('vendor_model', models.CharField(blank=True, help_text='Модель', max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='services/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True, help_text='Ключивые слова')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('accessories', models.ManyToManyField(blank=True, to='shop.Product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shop.Category')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='services',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'slug')},
        ),
    ]
