# Generated by Django 2.1.4 on 2019-02-13 23:29

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Список тегов, разделенных запятыми', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
