# Generated by Django 2.1.4 on 2019-01-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Каталог товара (расходные материалы, компьютеры и комплетующие и т д)', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.Category'),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shop.Category'),
        ),
    ]
