# Generated by Django 2.1.4 on 2019-02-11 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Процент скидка', max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('stock_start', models.DateTimeField()),
                ('stock_end', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ('product',),
            },
        ),
    ]
