# Generated by Django 2.1.4 on 2019-02-11 01:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_fild',
        ),
        migrations.RemoveField(
            model_name='product',
            name='format_fild',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specific_filds',
        ),
        migrations.RemoveField(
            model_name='services',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Каталог товара (расходные материалы, компьютеры и комплетующие и т д)', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.TextField(blank=True, help_text='Ключивые слова (тонер, материнская плата, пружина)'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='discount_percent',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.07'), '7%'), (Decimal('0.15'), '15%'), (Decimal('0.20'), '20%'), (Decimal('0.25'), '25%'), (Decimal('0.30'), '30%')], decimal_places=2, help_text='Процент скидка', max_digits=5, null=True),
        ),
    ]
