# Generated by Django 2.1.4 on 2019-02-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, upload_to='service/%Y/%m/%d'),
        ),
    ]
