# Generated by Django 2.1.4 on 2019-01-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190130_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='vendor',
            field=models.CharField(blank=True, help_text='Производитель', max_length=200),
        ),
        migrations.AddField(
            model_name='services',
            name='vendor_model',
            field=models.CharField(blank=True, help_text='Модель', max_length=200),
        ),
    ]
