# Generated by Django 2.1.4 on 2019-02-13 23:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_test_fild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Характеристики товара'),
        ),
    ]
