# Generated by Django 2.1.4 on 2019-02-07 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190207_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='interest',
        ),
    ]
