# Generated by Django 2.1.4 on 2019-02-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_product_test_fild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_fild',
            field=models.CharField(blank=True, choices=[('', ''), ('bw', 'ЧБ'), ('color', 'Цветной')], help_text='BW, Color', max_length=50),
        ),
    ]
