# Generated by Django 2.1.4 on 2019-02-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20190214_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_fild',
            field=models.CharField(blank=True, choices=[('', ''), ('BW', 'BW'), ('color', 'Color')], help_text='BW, Color', max_length=50),
        ),
    ]
