# Generated by Django 2.1.4 on 2019-02-18 20:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20190214_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='available',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='product',
            name='action',
            field=models.BooleanField(default=False, help_text='Акции'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.03'), '3%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%'), (Decimal('0.06'), '6%'), (Decimal('0.07'), '7%'), (Decimal('0.08'), '8%'), (Decimal('0.09'), '9%'), (Decimal('0.10'), '10%'), (Decimal('0.11'), '11%'), (Decimal('0.12'), '12%'), (Decimal('0.13'), '13%'), (Decimal('0.14'), '14%'), (Decimal('0.15'), '15%'), (Decimal('0.16'), '16%'), (Decimal('0.17'), '17%'), (Decimal('0.18'), '18%'), (Decimal('0.19'), '19%'), (Decimal('0.20'), '20%'), (Decimal('0.21'), '21%'), (Decimal('0.22'), '22%'), (Decimal('0.23'), '23%'), (Decimal('0.24'), '24%'), (Decimal('0.25'), '25%'), (Decimal('0.26'), '26%'), (Decimal('0.27'), '27%'), (Decimal('0.28'), '28%'), (Decimal('0.30'), '30%')], decimal_places=2, default=Decimal('0.00'), help_text='Процент скидка', max_digits=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
