# Generated by Django 2.1.4 on 2019-02-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20190218_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_percent',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='productstock',
            name='stock_end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='stock_start',
            field=models.DateTimeField(blank=True),
        ),
    ]
