# Generated by Django 2.1.4 on 2019-02-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20190218_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Процент скидка', max_digits=10),
        ),
    ]
