# Generated by Django 2.1.4 on 2019-02-22 10:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20190218_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.06'), help_text='Процент скидка', max_digits=10),
        ),
    ]
