# Generated by Django 2.1.4 on 2019-02-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('shop', '0028_auto_20190222_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygraphy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=400)),
                ('slug', models.SlugField(max_length=400)),
                ('image', models.ImageField(blank=True, upload_to='polygraphy/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('accessories', models.ManyToManyField(blank=True, to='shop.Product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygraphy', to='shop.Category')),
                ('flatpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flatpages.FlatPage')),
            ],
            options={
                'verbose_name': 'Полиграфия',
                'verbose_name_plural': 'Полиграфия',
                'ordering': ('name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='polygraphy',
            index_together={('id', 'slug')},
        ),
    ]
