# Generated by Django 2.1.4 on 2019-02-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20190222_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygraphy',
            name='accessories',
        ),
        migrations.AddField(
            model_name='polygraphy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='polygraphy',
            name='keywords',
            field=models.TextField(blank=True, help_text='Ключивые слова'),
        ),
        migrations.AlterField(
            model_name='polygraphy',
            name='image',
            field=models.ImageField(blank=True, upload_to='service/%Y/%m/%d'),
        ),
    ]
