# Generated by Django 2.1.4 on 2019-02-22 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20190222_2151'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='polygraphy',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='polygraphy',
            name='category',
        ),
        migrations.RemoveField(
            model_name='polygraphy',
            name='flatpage',
        ),
        migrations.DeleteModel(
            name='Polygraphy',
        ),
    ]
