# Generated by Django 2.1.4 on 2019-02-22 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('shop', '0031_auto_20190222_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygraphy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='polygraphy/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True, help_text='Ключивые слова')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygraphy', to='shop.Category')),
                ('flatpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flatpages.FlatPage')),
            ],
            options={
                'verbose_name': 'Полиграфия',
                'verbose_name_plural': 'Полиграфия',
            },
        ),
    ]
