# Generated by Django 2.1.4 on 2019-02-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_polygraphy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygraphy',
            name='category',
        ),
    ]
