# Generated by Django 2.1.4 on 2019-02-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_remove_polygraphy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygraphy',
            name='slug',
            field=models.SlugField(default=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='polygraphy',
            name='image',
            field=models.ImageField(blank=True, upload_to='polygraphy/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, upload_to='service/'),
        ),
    ]
