# Generated by Django 2.1.4 on 2019-02-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20190224_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygraphy',
            name='slug',
        ),
    ]
