# Generated by Django 2.1.4 on 2019-02-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_remove_polygraphy_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygraphy',
            name='slug',
            field=models.SlugField(default='True', max_length=400),
        ),
    ]
