# Generated by Django 2.1.4 on 2019-03-03 22:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20190225_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.CharField(default='cw', help_text='Поставщик', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_fild',
            field=models.CharField(blank=True, choices=[('BW', 'BW'), ('Color', 'Color')], help_text='BW, Color', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Процент скидка', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='format_fild',
            field=models.CharField(blank=True, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('A8', 'A8'), ('A9', 'A9'), ('A10', 'A10')], help_text='A3,A4', max_length=50),
        ),
    ]
