# Generated by Django 2.1.4 on 2019-03-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20190303_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='provider',
            field=models.CharField(help_text='Поставщик', max_length=20),
        ),
    ]
