# Generated by Django 2.1.4 on 2019-03-10 12:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20190303_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Цена со скидкой', max_digits=10),
        ),
        migrations.DeleteModel(
            name='ProductStock',
        ),
    ]
