# Generated by Django 2.1.4 on 2019-03-30 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_remove_product_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end_action',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 30, 7, 27, 16, 548029, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='start_action',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 30, 7, 27, 22, 227574, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
