# Generated by Django 2.1.4 on 2019-04-15 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_auto_20190330_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='accessories',
            field=models.ManyToManyField(blank=True, editable=False, related_name='_product_accessories_+', to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_action',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_action',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Остатоки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(help_text='Артикул, парт номер', max_length=200, unique=True),
        ),
    ]
