# Generated by Django 2.1.4 on 2019-07-01 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Новой Почтой', 'Новой Почтой')], default=True, max_length=50, verbose_name='Спопсоб доставки')),
                ('pay_method', models.CharField(choices=[('Ниличные', 'Ниличные'), ('Безналичный расчет', 'Безналичный расчет')], default=True, max_length=50, verbose_name='Спопсоб оплаты')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('sur_name', models.CharField(max_length=50, verbose_name='Отчесво')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('department_np', models.CharField(max_length=300, verbose_name='НП №')),
                ('mobile_phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('note_text', models.TextField(blank=True, max_length=512, verbose_name='Дополнения, пожелания, заметки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Product')),
            ],
        ),
    ]
